[package]
name = "wasm_ws"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.45"
futures = "0.3"
wasm-bindgen-futures = "0.4"

[dependencies.web-sys]
version = "0.3.22"
features = ["ErrorEvent", "MessageEvent", "WebSocket"]
